import Cocoa
import VietEngine

/// Lịch sử clipboard (chỉ lưu trong bộ nhớ, mất khi thoát app) và chuyển mã nội dung clipboard.
final class ClipboardManager: NSObject {
    private let settings = AppSettings.shared
    private let pasteboard = NSPasteboard.general
    private(set) var history: [String] = []
    private var lastChangeCount: Int
    private var timer: Timer?
    private let maxItems = 25
    /// Báo một thông điệp ngắn ra màn hình (AppDelegate hiện HUD).
    var notify: ((String) -> Void)?

    /// Nội dung đánh dấu là mật khẩu / tạm thời (1Password, Bitwarden, Keychain…): không bao giờ lưu.
    private let sensitiveTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType", "com.agilebits.onepassword", "com.bitwarden.desktop.concealed",
    ]

    override init() {
        lastChangeCount = pasteboard.changeCount
        super.init()
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
    }

    func clearHistory() { history.removeAll() }

    private func poll() {
        let count = pasteboard.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard settings.clipboardHistory else { return }
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: sensitiveTypes),
              let text = pasteboard.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        history.removeAll { $0 == text }
        history.insert(text, at: 0)
        if history.count > maxItems { history.removeLast(history.count - maxItems) }
    }

    private func write(_ text: String) {
        pasteboard.clearContents()
        pasteboard.setString(text, forType: .string)
    }

    // MARK: - Chuyển mã

    enum Conversion: CaseIterable {
        case removeDiacritics, fromTCVN3, fromVNI, precomposed, upper, lower, title
        var title: String {
            switch self {
            case .removeDiacritics: return "Bỏ dấu (Tiếng Việt → Tieng Viet)"
            case .fromTCVN3: return "TCVN3 (ABC) → Unicode"
            case .fromVNI: return "VNI Windows → Unicode"
            case .precomposed: return "Unicode tổ hợp → dựng sẵn"
            case .upper: return "CHỮ HOA"
            case .lower: return "chữ thường"
            case .title: return "Viết Hoa Đầu Từ"
            }
        }
        func apply(_ s: String) -> String {
            switch self {
            case .removeDiacritics: return TextConverter.removeDiacritics(s)
            case .fromTCVN3: return TextConverter.fromTCVN3(s)
            case .fromVNI: return TextConverter.fromVNI(s)
            case .precomposed: return TextConverter.precomposed(s)
            case .upper: return TextConverter.uppercased(s)
            case .lower: return TextConverter.lowercased(s)
            case .title: return TextConverter.titleCased(s)
            }
        }
    }

    func convert(_ c: Conversion) {
        guard let text = pasteboard.string(forType: .string) else {
            notify?("Clipboard không có chữ")
            return
        }
        write(c.apply(text))
        notify?("Đã chuyển clipboard – bấm ⌘V để dán")
    }

    // MARK: - Menu

    /// Thêm các mục chuyển mã vào một menu (dùng chung cho menu bật nhanh và menu thanh trạng thái).
    func addConversionItems(to menu: NSMenu) {
        for c in Conversion.allCases {
            let item = menu.addItem(withTitle: c.title, action: #selector(convertItem(_:)), keyEquivalent: "")
            item.target = self
            item.representedObject = c.title
        }
    }

    @objc private func convertItem(_ item: NSMenuItem) {
        guard let c = Conversion.allCases.first(where: { $0.title == item.representedObject as? String }) else { return }
        convert(c)
    }

    /// Menu bật bằng phím tắt, hiện tại vị trí con trỏ chuột: chọn mục lịch sử để dán, hoặc chuyển mã clipboard.
    func showPopup() {
        let previous = NSWorkspace.shared.frontmostApplication
        let menu = NSMenu()
        var picked: String?

        if history.isEmpty {
            menu.addItem(withTitle: settings.clipboardHistory ? "Lịch sử clipboard trống" : "Lịch sử clipboard đang tắt",
                         action: nil, keyEquivalent: "").isEnabled = false
        } else {
            menu.addItem(withTitle: "Chọn để dán:", action: nil, keyEquivalent: "").isEnabled = false
            for (i, text) in history.enumerated() {
                let item = ClosureMenuItem(title: Self.preview(text), key: i < 9 ? "\(i + 1)" : "") { picked = text }
                item.toolTip = String(text.prefix(500))
                menu.addItem(item)
            }
        }
        menu.addItem(.separator())
        let conv = NSMenuItem(title: "Chuyển mã clipboard", action: nil, keyEquivalent: "")
        conv.submenu = NSMenu()
        addConversionItems(to: conv.submenu!)
        menu.addItem(conv)
        menu.addItem(ClosureMenuItem(title: "Xoá lịch sử", key: "") { [weak self] in self?.clearHistory() })

        NSApp.activate(ignoringOtherApps: true)
        menu.popUp(positioning: nil, at: NSEvent.mouseLocation, in: nil)
        previous?.activate()

        guard let text = picked else { return }
        write(text)
        // Chờ ứng dụng cũ nhận lại focus rồi mới dán
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.15) { Self.pasteKeystroke() }
    }

    private static func preview(_ s: String) -> String {
        let one = s.replacingOccurrences(of: "\n", with: " ⏎ ").trimmingCharacters(in: .whitespaces)
        return one.count > 60 ? String(one.prefix(60)) + "…" : one
    }

    /// Gửi ⌘V (gắn dấu của Gõ Việt để KeyTap bỏ qua).
    static func pasteKeystroke() {
        let src = CGEventSource(stateID: .privateState)
        for down in [true, false] {
            guard let e = CGEvent(keyboardEventSource: src, virtualKey: 9, keyDown: down) else { continue }
            e.flags = .maskCommand
            e.setIntegerValueField(.eventSourceUserData, value: OutputSender.magic)
            e.post(tap: .cgSessionEventTap)
        }
    }
}

/// Mục menu chạy một closure khi được chọn.
final class ClosureMenuItem: NSMenuItem {
    private let handler: () -> Void
    init(title: String, key: String, handler: @escaping () -> Void) {
        self.handler = handler
        super.init(title: title, action: #selector(run), keyEquivalent: key)
        target = self
    }
    required init(coder: NSCoder) { fatalError("không dùng") }
    @objc private func run() { handler() }
}
